global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/s3slower.rules.yml"

scrape_configs:
  - job_name: "s3slower"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:9000"]
        labels:
          instance: "localhost"
