// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEventT struct {
	_               structs.HostLayout
	TimestampUs     uint64
	LatencyUs       uint64
	Pid             uint32
	Tid             uint32
	Fd              uint32
	Comm            [16]int8
	ReqSize         uint32
	RespSize        uint32
	ActualRespBytes uint32
	IsPartial       uint8
	ClientType      uint8
	Pad             [2]uint8
	Data            [512]int8
	RespData        [128]int8
	_               [4]byte
}

type bpfReadArgsT struct {
	_      structs.HostLayout
	BufPtr uint64
	Fd     uint32
	Source uint8
	Pad    [3]uint8
}

type bpfReqInfoT struct {
	_          structs.HostLayout
	StartTime  uint64
	ReqSize    uint32
	Fd         uint32
	ClientType uint8
	Comm       [16]int8
	Data       [512]int8
	_          [7]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeSysRead        *ebpf.ProgramSpec `ebpf:"kprobe_sys_read"`
	KprobeSysRecvfrom    *ebpf.ProgramSpec `ebpf:"kprobe_sys_recvfrom"`
	KprobeSysSendto      *ebpf.ProgramSpec `ebpf:"kprobe_sys_sendto"`
	KprobeSysWrite       *ebpf.ProgramSpec `ebpf:"kprobe_sys_write"`
	KretprobeSysRead     *ebpf.ProgramSpec `ebpf:"kretprobe_sys_read"`
	KretprobeSysRecvfrom *ebpf.ProgramSpec `ebpf:"kretprobe_sys_recvfrom"`
	UprobeGnutlsRecv     *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_recv"`
	UprobeGnutlsSend     *ebpf.ProgramSpec `ebpf:"uprobe_gnutls_send"`
	UprobePrRead         *ebpf.ProgramSpec `ebpf:"uprobe_pr_read"`
	UprobePrWrite        *ebpf.ProgramSpec `ebpf:"uprobe_pr_write"`
	UprobeSslRead        *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UretprobeGnutlsRecv  *ebpf.ProgramSpec `ebpf:"uretprobe_gnutls_recv"`
	UretprobePrRead      *ebpf.ProgramSpec `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead     *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap   *ebpf.MapSpec `ebpf:"config_map"`
	EventHeap   *ebpf.MapSpec `ebpf:"event_heap"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	ReadArgsMap *ebpf.MapSpec `ebpf:"read_args_map"`
	ReqHeap     *ebpf.MapSpec `ebpf:"req_heap"`
	ReqMap      *ebpf.MapSpec `ebpf:"req_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap   *ebpf.Map `ebpf:"config_map"`
	EventHeap   *ebpf.Map `ebpf:"event_heap"`
	Events      *ebpf.Map `ebpf:"events"`
	ReadArgsMap *ebpf.Map `ebpf:"read_args_map"`
	ReqHeap     *ebpf.Map `ebpf:"req_heap"`
	ReqMap      *ebpf.Map `ebpf:"req_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.EventHeap,
		m.Events,
		m.ReadArgsMap,
		m.ReqHeap,
		m.ReqMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeSysRead        *ebpf.Program `ebpf:"kprobe_sys_read"`
	KprobeSysRecvfrom    *ebpf.Program `ebpf:"kprobe_sys_recvfrom"`
	KprobeSysSendto      *ebpf.Program `ebpf:"kprobe_sys_sendto"`
	KprobeSysWrite       *ebpf.Program `ebpf:"kprobe_sys_write"`
	KretprobeSysRead     *ebpf.Program `ebpf:"kretprobe_sys_read"`
	KretprobeSysRecvfrom *ebpf.Program `ebpf:"kretprobe_sys_recvfrom"`
	UprobeGnutlsRecv     *ebpf.Program `ebpf:"uprobe_gnutls_recv"`
	UprobeGnutlsSend     *ebpf.Program `ebpf:"uprobe_gnutls_send"`
	UprobePrRead         *ebpf.Program `ebpf:"uprobe_pr_read"`
	UprobePrWrite        *ebpf.Program `ebpf:"uprobe_pr_write"`
	UprobeSslRead        *ebpf.Program `ebpf:"uprobe_ssl_read"`
	UprobeSslWrite       *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UretprobeGnutlsRecv  *ebpf.Program `ebpf:"uretprobe_gnutls_recv"`
	UretprobePrRead      *ebpf.Program `ebpf:"uretprobe_pr_read"`
	UretprobeSslRead     *ebpf.Program `ebpf:"uretprobe_ssl_read"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeSysRead,
		p.KprobeSysRecvfrom,
		p.KprobeSysSendto,
		p.KprobeSysWrite,
		p.KretprobeSysRead,
		p.KretprobeSysRecvfrom,
		p.UprobeGnutlsRecv,
		p.UprobeGnutlsSend,
		p.UprobePrRead,
		p.UprobePrWrite,
		p.UprobeSslRead,
		p.UprobeSslWrite,
		p.UretprobeGnutlsRecv,
		p.UretprobePrRead,
		p.UretprobeSslRead,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
